### PR TITLE
Allow to use a plain condition

### PR DESCRIPTION
**Pull request by ReklatsMasters**
Example:
```js
const ifstream  = require('ternary-stream');
const zlib      = require('zlib');

// ...http.get
var enc = response.headers['content-encoding'];
response
    .pipe(ifstream(enc == 'gzip', zlib.createGunzip()))      // condition is not a function
    .pipe(ifstream(enc == 'deflate', zlib.createInflate()))
    // .pipe
```

### CODE REVIEW

**Comment by robrich** [comment]
Thanks for the PR.  Added to https://github.com/robrich/gulp-match/blob/master/index.js#L10

**Comment by dfcreative** [comment]
@robrich just wonder why that was not merged? Seems to be reasonable and useful for many cases.

**Comment by robrich** [comment]
@dfcreative: It was merged, just into a higher level module instead of here.  Do you have a use-case where it's more helpful here instead?

**Comment by dfcreative** [comment]
Yes, I was going to use it at plotly [here](https://github.com/plotly/plotly.js/pull/2187/files#diff-75cb9bb70bfe9c024a0191bc048593a6R53). Since codestyle policy is ES5, it is just uncomfy and redundant to create a whole `function` when we have condition `outputMinified` already.

**Comment by robrich** [comment]
That's a good reason.  I'm thinking this will be even better:

```
if (typeof _condition === 'boolean') {
  return _condition ? trueStream : falseStream;
}
```

See any issues with this short-cut?

**Comment by dfcreative** [comment]
@robirch makes perfect sense to me, unless condition is false and falseStream is undefined - probably we should return original stream then?

**Pull request closed without merging**
